services:
  database:
    image: postgres
    restart: always
    ports:
      - "10123:5432"
    environment:
      POSTGRES_PASSWORD: "education!"
    volumes:
      - chronoquest_dbdata:/var/lib/postgresql/data
  
volumes:
  chronoquest_dbdata:  